version: "3"

services:
  db:
    image: postgres
    container_name: automobilisto_catalog__db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: automobilisto_catalog
    ports:
    - "5493:5432"
    volumes:
    - db:/data/db

volumes:
  db: {}
